typography_spectrum: 0.5456686555407941
color:
  brandStrength: 0.35330533399246633
  lightness: 0.18521723966114223
  saturation: 0.45481105986982584
  rhythmicContrast: 0.15746649191714823
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.7500010111834854
name: Will Gurley
title: Portfolio
description: Design & Art
